[Icon Theme]
Name=macos-icons
Comment=MacOSX 3D Glassmorphism style icon theme for Linux.
Inherits=Adwaita,hicolor,breeze
Example=folder

# KDE/Plasma Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,96,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
FollowsColorScheme=true

KDE-Extensions=.svg

# Directory list
Directories=apps/scalable,places/scalable


[apps/scalable]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable


[places/scalable]
Size=64
Context=Places
MinSize=32
MaxSize=512
Type=Scalable
